require: rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
  - "bin/**/*"
  - "db/**/*"
  - "tmp/**/*"
  - "vendor/**/*"
  - "config/environments/*"

Bundler/OrderedGems:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Metrics/AbcSize:
  CountRepeatedAttributes: false
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  CountAsOne: ['array', 'hash', 'heredoc']
Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc']
Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']
Metrics/ModuleLength:
  CountAsOne: ['array', 'hash', 'heredoc']

Rails/BulkChangeTable:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false
