meta_name: "Vin de copain"
meta_title: "Vin de copain - Partager vos adresses entre ami(e)s"
meta_description: "U moyen simple de partager avec votre entourage vos bonnes adresses de vignerons"
meta_image: "default_wine.avif" # should exist in `app/assets/images/`
# twitter_account: "@your_twitter_account"   # required for Twitter Cards
